fabric8io/gofabric8

README.md
cmds/deploy.go

I added a new param apidomain which is used for pod template if it is different then domain param. adjusted readme accordingly

add an --apidomain param to the deploy command

---

cmds/common.go
cmds/deploy.go

Default value for arch is runtime.GOARCH

Add option --arch for deploy so that arm based images can be also deployed from outside.

---

cmds/volumes.go

Fix check for Vagrantfile in hostpath volume creation

---

cmds/deploy.go
cmds/volumes.go

Resolved Issue #208 , since the PVC are created before actual PVs are created, the Volume reference inside the PVC's which are in status `Pending` or 'Lost` are dangling or pointing to __default__ namespace, since default namespace PV's/PVC are bound to each other, the namespace PV/PVC are not bound, hence the required pods are in Creation State for long time.
Approach:
* after new PV are created for PVC in status `Pending` or 'Lost`, we delete the PVC and recreate them to bind it.
Another thought would be to refrain from creating PVC's during deploy ? ( I am not sure this is valid  thought)
Sample output 
https://gist.github.com/kameshsampath/a70ce3ff57d1f552a2434d525a6a2118

Resolved Issue#208 - For validation

---

cmds/volumes.go

Fix volume paths when running on Windows

---

cmds/deploy.go

deploy the exposecontroller AFTER we create the config for it

---

cmds/install.go
cmds/start.go

improve install function and download oc client

---

cmds/install.go

Use kubernetes stable release url for kube release

---

README.md

Remove backslash from $PATH

---

cmds/install.go

OC client wasn't installed properly on Linux.
I guess it was assumed that it was already installed by the OS packages but I think it may be better to still have it download to make sure we have the right version (and avoid non compatibility bugs) for new users.

Fix OpenShift client install on Linux

---

cmds/start.go

better error message when driver is not installed

---

cmds/environ.go
gofabric8.go

gofabric8 now has a delete environ command.  Similar to the get environ command.

Added delete environ command

---

cmds/completion.go
cmds/cruds.go
cmds/environ.go
gofabric8.go

Add bash and zsh completion from kubectl
Closes #222

Add shell completion

---

cmds/cleanup.go
cmds/cruds.go
gofabric8.go

- Move gofabric8 destroy to gofabric8 delete system
Fixes #400

Add delete apps commands

---

cmds/environ.go
cmds/environ_test.go

Hopefully this should be the beginning for more tests

Add test for create_environ

---

cmds/environ.go
gofabric8.go

I am not so sure about the option naming, i can take suggestions

add a command line switch to specify a project

---

cmds/common.go

Do not show banner when running under windows

---

cmds/cleanup.go

Change the way we are deleting the system, we are now deleting first the
PVC and delete the project directly which should delete all resources.
The -jenkins project is a special case and will need some tricks to get
deleted, avoiding it for now.

Cleanup improvement

---

cmds/cleanup.go
cmds/cruds.go

allow deleting specific apps which basically goes over all resources and delete things with label project=appname as discussed with @jstrachan 
here https://github.com/fabric8io/gofabric8/issues/400#issuecomment-312222886
There was some other fixes along the way but I was not in mood of creating yet another pr,
This probably going to conflict with #462 but as they say here "c'est la vie", may the first be merged and i'll fix the conflict in the other, "amen!"

add delete app

---

cmds/deploy.go

lets fail the install if using kubernetes < 1.7
also lets ensure on kubernetes we try label a node for the ingress controller
fixed up install of CRDs on kubernetes

fixes for installing fabric8-system on kubernetes

---

cmds/deploy.go

Not the prettiest way to do it but that would do

Wait for default storageclass

---

cmds/clean_apps.go
cmds/clean_content_repo.go
cmds/clean_jenkins.go
cmds/clean_mvn_local_repo.go
cmds/clean_tenant.go
cmds/cleanup.go
cmds/common.go
cmds/deploy.go
cmds/log.go
cmds/test.go
cmds/upgrade.go
gofabric8.go

to test the current tenant using an end to end pipeline
polish the clean mvn-local-repo logic

lets add a new test command

---

cmds/clean_jenkins.go
cmds/common.go
cmds/cruds.go
cmds/tenant.go
cmds/tenant_check.go
cmds/tenant_delete.go
cmds/tenant_upgrade.go
cmds/wait_for.go

to check a tenant or delete a tenant
also made tenant clean/delete commands appear under tenant and the clean/delete commands

add tenant commands

---

cmds/tenant_delete.go

this seems to clear out the PVs after the tenant is recreated

lets remove the PVCs when deleting the tenant

---

cmds/log.go

this seems to clear out the PVs after the tenant is recreated

	allow the log command take a namespace parameter

---

cmds/deploy.go
cmds/start.go
gofabric8.go

Just being pedantic about some spellings etc. But hey, I am contributing to gofabric8 ... :)

Fixing some simple typos in gofabric8 commands help text.

---

cmds/e2e.go
gofabric8.go

so that we can automate running e2e tests on clusters we re-install/update as part of CI / CD

first spike of a CLI to run e2e tests on a cluster

---

cmds/e2e.go

also lets work around issues on OpenShift

return success or failure better

---

cmds/e2e.go
cmds/e2e_secret.go

so we can customise the E2E tests via the CLI

allow further parameterisation of the e2e command

---

Makefile

This has been a bit of a pet of mine to get the compile time.
By default we run go fmt which can be awfully slow and then change
the timestamp so make(1) cannot detect if there is a change or not and
alway recompile[1]
It does run by default the unittests on every make command which is
something that takes quite some time as well.
Let's move those in the standard `test` target making sure this is
available in make release which arguably is the best place to have
those.
[1] which break my editor on the fly compilation for me.

Optimize Makefile

---

cmds/erase_pvc.go
gofabric8.go

Add Erase PVC command

---

cmds/bdd_env.go

so that the test code is in sync with the updatebot / import job credentials

lets add the github username / pwd

---

cmds/common.go
cmds/version.go

Try to print as much as possible from mini/shift/kube and the clients
Issue #584

Improve version with server and client information

---

cmds/service.go

We are using routes instead of services on OpenShift to get the external URL.
We go over all projects available if the default one doesn't have it.
This would handle the case for issue #576

Detect services with routes on OpenShift

---

cmds/deploy.go

Fix printing info about remote install

---

cmds/e2e_console.go
gofabric8.go

as on minishift we cannot see the fabric8 namespace from inside jenkins SA

lets add a helper command to populate the console

---

README.md
cmds/deploy.go

- The overall structure, add TOC
- Explain the install command; confusing since we have a deploy as well
- Minor fixes here and there

Improve the README

---

README.md

Document missing commands in README
